sudo: false
language: node_js # 指定语言环境
node_js:
  - 10 # 指定 NodeJS 版本
dist: trusty # 指定系统版本。trusty 是指 Ubuntu 14.04 发行版的名称

branches: # 指定要构建的分支
  only: # only 表示只构建以下分支
  - blog-source

install: # 在安装项目环境阶段需要运行的命令，一条一行
    # 全局安装 Hexo
  - npm install -g hexo
    # 全局安装 Hexo 命令行工具，因为我们是命令行操作
  - npm install -g hexo-cli
    # 安装 package.json 中的依赖
  - npm install
  - npm install hexo-deployer-git --save

script: # 在构建阶段需要运行的命令，一条一行
  - hexo clean
  - hexo generate # Hexo 常规命令，执行清理和生成

after_success: # 在构建成功后要运行的命令，构建失败不会执行，其他同上
  - git config --global user.name "danny.travis"
  - git config --global user.email "dannywu201407@gmail.com"
    # - sed -i'' - sed -i'' "s~git@github.com:dannywu2014/dannywu2014.github.io.git~https://${REPO_TOKEN}@github.com/dannywu2014/dannywu2014.github.io.git~" _config.yml
  - sed -i'' -i'' "s+git@github.com:dannywu2014/dannywu2014.github.io.git+https://${REPO_TOKEN}@github.com/dannywu2014/dannywu2014.github.io.git+" _config.yml
  - hexo deploy # 通过 hexo 的 deploy 命令部署博客
    #- hexo deploy > /dev/null # 通过 hexo 的 deploy 命令部署博客
